$axure.loadCurrentPage({
  "url":"快速注册资料检索.html",
  "generationDate":new Date(1452351349026.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"7170717981b244b58c28ecb38ccd8bb1",
    "type":"Axure:Page",
    "name":"快速注册资料检索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ebfa2c43e0e046709d8f889c85105606",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"7e530a7abf404c78b982e664cb078151",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"24px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "location":{
              "x":29,
              "y":102},
            "size":{
              "width":375,
              "height":50},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"9"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7253a83e9b774980ab01ee363a601899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"24px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "location":{
                  "x":29,
                  "y":102},
                "size":{
                  "width":375,
                  "height":50},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"9"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u29.png"}},
{
          "id":"8dfdfa546f0b476e89b0b8fc741fa70f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":44,
              "y":320},
            "size":{
              "width":344,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af03c8636e8846059ba945a1e8551351",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":44,
                  "y":320},
                "size":{
                  "width":344,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速注册资料检索/u27.png"}},
{
          "id":"196d4e8f035346e2b32ea1c469ad429c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":43,
              "y":155},
            "size":{
              "width":347,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775d7dae6ec346b9b3dc90fdcb75dde8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35f822883e4b49e085dee968f4bc1337",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"0f9a12bbd85e4237943be172a676faaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":0},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8a2bf3f533c428e90376a69696416c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"fe1ee197d36c4726b0dec2f5fa26d9d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b5291a4f1b64158b1ae644d098b4937",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"a34acd05ec2c483f864f5502ef956533",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":90},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96a47269545a410daf391fcb2637bc1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":90},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"a1cf005f811c4229ba5d927fe3b9ed58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f6967fc928848009c6ff113e184c64a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"0c697533716e4555bd56654397ccb308",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":60},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f2d5d4df2bc4edeada9164403ca77c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":60},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"647187fc89c84892b88809028ad992d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4545f325edbb43acaa122707bc65d7ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"edd7dd6fa0ef45dc8d1ebd1b46b978df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":30},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bfdd6ed671924f239d01fa66182bbe14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":30},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}}]},
{
          "id":"b02424a576814d86b3408a7368e5dfdb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":178,
              "y":157},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6f83af15aee54007bdf6b678a0397540",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":178,
              "y":189},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"387fc0a45031420b86f18d0ad0a0a49c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":178,
              "y":218},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3610e5ba175f47c8a08a47fd2ea405f1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":178,
              "y":247},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5d01304734704abb953e345cc08cafe1",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":229,
              "y":276},
            "size":{
              "width":150,
              "height":40},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a1d62875b449d99dd40ba5653240ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":229,
                  "y":276},
                "size":{
                  "width":150,
                  "height":40},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34.png",
            "mouseDown~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34_mouseDown.png"}},
{
          "id":"3e71d9102bfd471683ea4ceb31337e27",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":226,
              "y":658},
            "size":{
              "width":150,
              "height":40},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a08742140bc496fa0e067d004affdaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":226,
                  "y":658},
                "size":{
                  "width":150,
                  "height":40},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34.png",
            "mouseDown~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34_mouseDown.png"}}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "ebfa2c43e0e046709d8f889c85105606":{
      "scriptId":"u0",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u1"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u2"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u3"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u4"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u5"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u6"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u7"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u8"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u9"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u10"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u11"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u12"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u13"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u14"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u15"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u16"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u17"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u18"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u19"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u20"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u21"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u22"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u23"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u24"}},
    "7e530a7abf404c78b982e664cb078151":{
      "scriptId":"u25"},
    "7253a83e9b774980ab01ee363a601899":{
      "scriptId":"u26"},
    "8dfdfa546f0b476e89b0b8fc741fa70f":{
      "scriptId":"u27"},
    "af03c8636e8846059ba945a1e8551351":{
      "scriptId":"u28"},
    "196d4e8f035346e2b32ea1c469ad429c":{
      "scriptId":"u29"},
    "775d7dae6ec346b9b3dc90fdcb75dde8":{
      "scriptId":"u30"},
    "35f822883e4b49e085dee968f4bc1337":{
      "scriptId":"u31"},
    "0f9a12bbd85e4237943be172a676faaa":{
      "scriptId":"u32"},
    "f8a2bf3f533c428e90376a69696416c3":{
      "scriptId":"u33"},
    "647187fc89c84892b88809028ad992d0":{
      "scriptId":"u34"},
    "4545f325edbb43acaa122707bc65d7ed":{
      "scriptId":"u35"},
    "edd7dd6fa0ef45dc8d1ebd1b46b978df":{
      "scriptId":"u36"},
    "bfdd6ed671924f239d01fa66182bbe14":{
      "scriptId":"u37"},
    "a1cf005f811c4229ba5d927fe3b9ed58":{
      "scriptId":"u38"},
    "8f6967fc928848009c6ff113e184c64a":{
      "scriptId":"u39"},
    "0c697533716e4555bd56654397ccb308":{
      "scriptId":"u40"},
    "8f2d5d4df2bc4edeada9164403ca77c4":{
      "scriptId":"u41"},
    "fe1ee197d36c4726b0dec2f5fa26d9d3":{
      "scriptId":"u42"},
    "2b5291a4f1b64158b1ae644d098b4937":{
      "scriptId":"u43"},
    "a34acd05ec2c483f864f5502ef956533":{
      "scriptId":"u44"},
    "96a47269545a410daf391fcb2637bc1b":{
      "scriptId":"u45"},
    "b02424a576814d86b3408a7368e5dfdb":{
      "scriptId":"u46"},
    "6f83af15aee54007bdf6b678a0397540":{
      "scriptId":"u47"},
    "387fc0a45031420b86f18d0ad0a0a49c":{
      "scriptId":"u48"},
    "3610e5ba175f47c8a08a47fd2ea405f1":{
      "scriptId":"u49"},
    "5d01304734704abb953e345cc08cafe1":{
      "scriptId":"u50"},
    "a6a1d62875b449d99dd40ba5653240ef":{
      "scriptId":"u51"},
    "3e71d9102bfd471683ea4ceb31337e27":{
      "scriptId":"u52"},
    "8a08742140bc496fa0e067d004affdaa":{
      "scriptId":"u53"}}});