$axure.loadCurrentPage({
  "url":"我的印章___重复购买.html",
  "generationDate":new Date(1452351350550.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"4c86d3dc9fc944bd900753488a40fcec",
    "type":"Axure:Page",
    "name":"我的印章 | 重复购买",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b66dfe374d8741589dfa6b3869edc092",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"2e0f6a24debe4ad38a71b6a29c061cd4",
          "label":"ButtonPrimary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "baseStyle":"d29cc72b6c974b5ea46614e4789869b0",
            "location":{
              "x":194,
              "y":712},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "cornerRadiusTopLeft":"41"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e5eede3495747a8af8d2928a573a1c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "baseStyle":"d29cc72b6c974b5ea46614e4789869b0",
                "location":{
                  "x":194,
                  "y":712},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "cornerRadiusTopLeft":"41"},
              "adaptiveStyles":{
}}],
          "annotation":{
            "说明":"这里的数量是显示购物车里印章总数<br>"},
          "images":{
            "normal~":"images/印章信息输入___注册监理工程师/buttonprimary_u63.png"}},
{
          "id":"50d564bff3e043058529c6ee09056d24",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":270},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "说明":"点击再次购买，会在购物车中增加同样的印章，可进行修改"}},
{
          "id":"f61d68e8719c42c8b7e59d5bd07ecff9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":103},
            "size":{
              "width":372,
              "height":458}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a184b841a30c466a96af014c4a070b2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":103},
                "size":{
                  "width":372,
                  "height":458}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u28.png"}},
{
          "id":"b365824bd05b4643982af4865caf889a",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":306,
              "y":270},
            "size":{
              "width":90,
              "height":30},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f257819091b84417b4c9a62fd4521a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":306,
                  "y":270},
                "size":{
                  "width":90,
                  "height":30},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "说明":"点击重复购买，会在购物车中增加同样的印章，可进行人名等修改"},
          "images":{
            "normal~":"images/我的印章___重复购买/buttonbigsecondary_u30.png",
            "mouseDown~":"images/我的印章___重复购买/buttonbigsecondary_u30_mouseDown.png"}},
{
          "id":"32ad083dc17f4a0dbe0d88f1af878041",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":307,
              "y":343},
            "size":{
              "width":90,
              "height":30},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"491103a8a7e44247b8301299df4809ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":307,
                  "y":343},
                "size":{
                  "width":90,
                  "height":30},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "说明":"点击重复购买，会在购物车中增加同样的印章，可进行人名等修改"},
          "images":{
            "normal~":"images/我的印章___重复购买/buttonbigsecondary_u30.png",
            "mouseDown~":"images/我的印章___重复购买/buttonbigsecondary_u30_mouseDown.png"}},
{
          "id":"69d23ca9c70f415a8aa23fdf061416fc",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":307,
              "y":499},
            "size":{
              "width":90,
              "height":30},
            "borderWidth":"2",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afea0d81cd243429032377ab0f3216d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":307,
                  "y":499},
                "size":{
                  "width":90,
                  "height":30},
                "borderWidth":"2",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "annotation":{
            "说明":"点击重复购买，会在购物车中增加同样的印章，可进行人名等修改"},
          "images":{
            "normal~":"images/我的印章___重复购买/buttonbigsecondary_u30.png",
            "mouseDown~":"images/我的印章___重复购买/buttonbigsecondary_u30_mouseDown.png"}},
{
          "id":"9c3d63dcc6484f4b8fedcaeec97a3133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":63,
              "y":200},
            "size":{
              "width":197,
              "height":32},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c73a5f113e24895b03551f733e14326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":63,
                  "y":200},
                "size":{
                  "width":197,
                  "height":32},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u36.png"}},
{
          "id":"60b1b49ca30b4498bb26ca94c9329e90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":112,
              "y":274},
            "size":{
              "width":184,
              "height":24},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e5bdb2a45c14c89b84911eb699608a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":112,
                  "y":274},
                "size":{
                  "width":184,
                  "height":24},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u38.png"}},
{
          "id":"1910e6da81d040a9a6246846ac4e3a44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":113,
              "y":343},
            "size":{
              "width":184,
              "height":24},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99882e4ce5248b3afeba7919328494f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":113,
                  "y":343},
                "size":{
                  "width":184,
                  "height":24},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u38.png"}},
{
          "id":"e96de51d6360432381a91abb915df9a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":63,
              "y":428},
            "size":{
              "width":197,
              "height":32},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed251797ec484183a501b810e990d917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":63,
                  "y":428},
                "size":{
                  "width":197,
                  "height":32},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u36.png"}},
{
          "id":"581889c53b644f9c85fcb43855ddd1de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":111,
              "y":490},
            "size":{
              "width":184,
              "height":24},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8651218ad00c475791fbb305f8d179eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":111,
                  "y":490},
                "size":{
                  "width":184,
                  "height":24},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的印章___重复购买/u38.png"}}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "b66dfe374d8741589dfa6b3869edc092":{
      "scriptId":"u0",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u1"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u2"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u3"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u4"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u5"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u6"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u7"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u8"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u9"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u10"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u11"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u12"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u13"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u14"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u15"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u16"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u17"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u18"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u19"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u20"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u21"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u22"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u23"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u24"}},
    "2e0f6a24debe4ad38a71b6a29c061cd4":{
      "scriptId":"u25"},
    "6e5eede3495747a8af8d2928a573a1c6":{
      "scriptId":"u26"},
    "50d564bff3e043058529c6ee09056d24":{
      "scriptId":"u27"},
    "f61d68e8719c42c8b7e59d5bd07ecff9":{
      "scriptId":"u28"},
    "a184b841a30c466a96af014c4a070b2e":{
      "scriptId":"u29"},
    "b365824bd05b4643982af4865caf889a":{
      "scriptId":"u30"},
    "f257819091b84417b4c9a62fd4521a2c":{
      "scriptId":"u31"},
    "32ad083dc17f4a0dbe0d88f1af878041":{
      "scriptId":"u32"},
    "491103a8a7e44247b8301299df4809ca":{
      "scriptId":"u33"},
    "69d23ca9c70f415a8aa23fdf061416fc":{
      "scriptId":"u34"},
    "7afea0d81cd243429032377ab0f3216d":{
      "scriptId":"u35"},
    "9c3d63dcc6484f4b8fedcaeec97a3133":{
      "scriptId":"u36"},
    "1c73a5f113e24895b03551f733e14326":{
      "scriptId":"u37"},
    "60b1b49ca30b4498bb26ca94c9329e90":{
      "scriptId":"u38"},
    "2e5bdb2a45c14c89b84911eb699608a6":{
      "scriptId":"u39"},
    "1910e6da81d040a9a6246846ac4e3a44":{
      "scriptId":"u40"},
    "d99882e4ce5248b3afeba7919328494f":{
      "scriptId":"u41"},
    "e96de51d6360432381a91abb915df9a1":{
      "scriptId":"u42"},
    "ed251797ec484183a501b810e990d917":{
      "scriptId":"u43"},
    "581889c53b644f9c85fcb43855ddd1de":{
      "scriptId":"u44"},
    "8651218ad00c475791fbb305f8d179eb":{
      "scriptId":"u45"}}});