<div class="stampcustomer"> 
<form action="<?php echo $this->getUrl('stampcustomer/index/ajax'); ?>" method="post" id="ajaxstampcustomer_form"> 
	<?php echo $this->getBlockHtml('formkey'); ?>
	<div class="fieldset"> 
		<ul class="form-list"> 
			<li> 
				<label for="a_state"><?php echo $this->__("注册区域"); ?></label>
				<?php $states = Mage::helper("stampcustomer")->getState(); ?>
				<?php if(count($states)>0): ?>
				<select name="a_state" id="a_state">
					<option value=""></option>
					<?php foreach($states as $state):?>
						<option value="<?php echo $state?>"> <?php echo $state?></option>
					<?php endforeach;?>
				</select>
				<?php else: ?>
				<input type="text" name="a_state" id="a_state" />
				<?php endif; ?>
			</li>
			<li> 
				<label for="a_name"><?php echo $this->__("姓名"); ?></label>
				<input type="text" name="a_name" id="a_name" />
			</li>
			<li> 
				<label for="a_company"><?php echo $this->__("公司"); ?></label>
				<input type="text" name="a_company" id="a_company" />
			</li>
			<li> 
				<label for="a_certtype"><?php echo $this->__("专业类型"); ?></label>
				<input type="text" name="a_certtype" id="a_certtype" value="一级注册建筑师" />
			</li>
			<li> 
				<label for="a_certsn"><?php echo $this->__("注册证书号"); ?></label>
				<input type="text" name="a_certsn" id="a_certsn" />
			</li>
			<li> 
				<label for="a_stampsn"><?php echo $this->__("印章号"); ?></label>
				<input type="text" name="a_stampsn" id="a_stampsn" />
			</li>
		</ul>
	</div>
	<a onclick="AjaxStampcustomer.submit(this)"><?php echo $this->__("查询");?></a>
</form>
<div class="results"> 

</div>
</div>
<script type="text/javascript">  
	//<!{CDATA[
		var AjaxStampcustomer  = new VarienForm('ajaxstampcustomer_form', true);
		AjaxStampcustomer.submit = function(button){
            if (this.validator.validate()) {
                var url = jQuery("#ajaxstampcustomer_form").attr('action');
                jQuery.ajax({
                    type: "POST",
                    url: url,
					dataType: "json", 
                    data:jQuery("#ajaxstampcustomer_form").serialize(),
                    success: function(json) {
                        if(json.status){
							jQuery(".results").empty().append(json.html);
						}else{
							jQuery(".results").empty().append(json.message);
						}
                    }
                });
            }
        }.bind(AjaxStampcustomer);
		
		jQuery(function($){
			$(".entry").click(function(){
				$(".stampcustomer").toggle();
			});
		})
	//]}>
	</script>
	
	<style type="text/css"> 
		.results table tr th{background-color:#d3ecff;}
		.results table tr,.stampcustomer a{cursor: pointer;  }
		.results table tr th,.results table tr td{padding:5px;  border-bottom: 1px solid #333;border-right: 1px solid #333;}
		.results table tr .last{border-right:none;}
		.stampcustomer{position: absolute; top: 185px; right: 0px;      background-color: #ddd;  padding: 30px;display:none;}
		.catalog-product-view .col-main{position: relative;}
	</style>