$axure.loadCurrentPage({
  "url":"印章信息输入___普通私章.html",
  "generationDate":new Date(1452351350138.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"fa3907665e574f35b9a1d5eda01c6ff8",
    "type":"Axure:Page",
    "name":"印章信息输入 | 普通私章",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"59e07fe126354b0f9615e63efd41cecb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"98bdbed9eb004e1bb544fc1ac2dcc64c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF76A9E0,
              "opacity":1},
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":29,
              "y":142},
            "size":{
              "width":375,
              "height":84},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0406c4098d27449e83bc470c658b0d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF76A9E0,
                  "opacity":1},
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":29,
                  "y":142},
                "size":{
                  "width":375,
                  "height":84},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/印章信息输入___普通私章/u25.png"}},
{
          "id":"62b013fe39cf4621bd00dd28cd23e1c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "location":{
              "x":39,
              "y":235},
            "size":{
              "width":357,
              "height":40},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b69b03760d5d44c4ac3a3ebccbbefd2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "location":{
                  "x":39,
                  "y":235},
                "size":{
                  "width":357,
                  "height":40},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/印章信息输入___一级注册建筑师/u44.png"}},
{
          "id":"ea8a7bd5d28e4d00a48d5059c11b28c8",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":45,
              "y":280},
            "size":{
              "width":347,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69a0d79a51ec498f8b2ef58dbb1510ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60a7e597f6864c2987730525664e0c55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"1d18455eff944266bacdeca73050c17b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":0},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fad3ca4f30aa48beab0c18d2249cb2ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"c4725534bb7b49fcbbb3b6702a48c0c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fa0c3aa6f714f449835cf86f48d6b69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"d5ddc0c990a7440198504b75550df549",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":90},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5e8ba95f572451a9fab75fb3a009041",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":90},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"14c6ed7a0ee14ee2afc0cf57f54bcd4f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7339ea51b09407c8f3251828088b1f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"27b58a8c479f440fa63e61f3c63ec09c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":60},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e2b6cbb6535491cba3bf78f6f775aa5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":60},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"9a3f61bb47954556ba5ff6eeaa2d4faa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4ca185b830446d1923e3b89b8c4fb41",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"d5c7ba68b2004a54bd1442ae8ab04c44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":30},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f8cb63d39664b28ad47e1dda3d858a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":30},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}}]},
{
          "id":"2e02f69654184cb7b816ff9fdb4e9175",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":282},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2eeb30e011144430b14328ab39f2ccc8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":314},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b30816ea3aeb4369a0fa51a358edbf9b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":342},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b40d2c69f00f420d8a14bf0ce63138bb",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":184,
              "y":374},
            "size":{
              "width":81,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b62ec23ef174f4491616595a3ae58a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":184,
                  "y":374},
                "size":{
                  "width":81,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"9f7e447a99304bde9e006ea7eedd6834",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":275,
              "y":374},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b64c2ac03504edfab21553144e9de89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":275,
                  "y":374},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"5fc467f2f43d4a8884db54ea794785cd",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":230,
              "y":415},
            "size":{
              "width":150,
              "height":40},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70559811add849368b040283d0825fa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":230,
                  "y":415},
                "size":{
                  "width":150,
                  "height":40},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了2个私章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了2个私章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34.png",
            "mouseDown~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34_mouseDown.png"}},
{
          "id":"223ff94698cf45daa43953d3f1cc2663",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"76635873ed5d45c4a1627735b63fa348"},
{
          "id":"a4525e5eaae74ab68d215bed8e158419",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":129},
            "size":{
              "width":85,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-选择印章类型-采购/u56_line.png"}}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "76635873ed5d45c4a1627735b63fa348":{
      "packageId":"76635873ed5d45c4a1627735b63fa348",
      "type":"Axure:Master",
      "name":"操作导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"19b3d41a9963435589c9b937e0460da6",
            "label":"操作导航状态",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":104},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"fd28231fa9814070a09aff6ceca23bbf",
                "label":"State4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"a6b7fcf8c10d42368892e1102b66fbaf",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":277,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"60660e7bbb0d4c4c94d0ddf78e19b0bf",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":277,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u38.png",
                      "selected~":"images/首页-选择印章类型-采购/u38_selected.png"}},
{
                    "id":"9f9baf27fea14a059b9be3da0d1ef825",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "location":{
                        "x":187,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8fcff2c504a34e3484112699bee30a6c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "location":{
                            "x":187,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"b4cd6d1140ec41d6aa60ee66792097c3",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":180,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9651f8f0dead4f38ab1c5a380de305cb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":180,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"02529ae43b9e44c0b41b26d31d899dc5",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":97,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b6a7d2948cea48a4a674ba51bd2b4c02",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":97,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"379fa31e4e1440878488b4662b173692",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":90,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d87fbf015e314371872e3894bf8d3b04",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":90,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"c88c696597a648eca0d1a0f3fd0f2c59",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":7,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6e57e6a09e6a4c5cb0f4478ad45c4033",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":7,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"edce9b88c1b84a97bcf179a7c5ba410a",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4d6529c5f2854300aa07a1c60ff2a181",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}}]}]},
{
            "id":"e11e63f0437e4e35a3583abef588e541",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":27,
                "y":103},
              "size":{
                "width":91,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4f9f006463574e26aba1e461594f7a34",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":128,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 印章信息输入 | 一级注册建筑师",
                        "target":{
                          "targetType":"page",
                          "url":"印章信息输入___一级注册建筑师.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d11ed9864dd44c1c9b0ff5d5f05016b0",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":218,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 输入物流与发票信息",
                        "target":{
                          "targetType":"page",
                          "url":"输入物流与发票信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1799b3c2583c4749b9b1214d15cc1eec",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":104},
              "size":{
                "width":94,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付",
                        "target":{
                          "targetType":"page",
                          "url":"支付.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "59e07fe126354b0f9615e63efd41cecb":{
      "scriptId":"u0",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u1"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u2"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u3"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u4"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u5"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u6"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u7"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u8"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u9"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u10"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u11"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u12"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u13"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u14"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u15"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u16"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u17"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u18"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u19"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u20"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u21"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u22"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u23"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u24"}},
    "98bdbed9eb004e1bb544fc1ac2dcc64c":{
      "scriptId":"u25"},
    "0406c4098d27449e83bc470c658b0d04":{
      "scriptId":"u26"},
    "62b013fe39cf4621bd00dd28cd23e1c5":{
      "scriptId":"u27"},
    "b69b03760d5d44c4ac3a3ebccbbefd2f":{
      "scriptId":"u28"},
    "ea8a7bd5d28e4d00a48d5059c11b28c8":{
      "scriptId":"u29"},
    "69a0d79a51ec498f8b2ef58dbb1510ad":{
      "scriptId":"u30"},
    "60a7e597f6864c2987730525664e0c55":{
      "scriptId":"u31"},
    "1d18455eff944266bacdeca73050c17b":{
      "scriptId":"u32"},
    "fad3ca4f30aa48beab0c18d2249cb2ae":{
      "scriptId":"u33"},
    "9a3f61bb47954556ba5ff6eeaa2d4faa":{
      "scriptId":"u34"},
    "c4ca185b830446d1923e3b89b8c4fb41":{
      "scriptId":"u35"},
    "d5c7ba68b2004a54bd1442ae8ab04c44":{
      "scriptId":"u36"},
    "2f8cb63d39664b28ad47e1dda3d858a2":{
      "scriptId":"u37"},
    "14c6ed7a0ee14ee2afc0cf57f54bcd4f":{
      "scriptId":"u38"},
    "b7339ea51b09407c8f3251828088b1f8":{
      "scriptId":"u39"},
    "27b58a8c479f440fa63e61f3c63ec09c":{
      "scriptId":"u40"},
    "6e2b6cbb6535491cba3bf78f6f775aa5":{
      "scriptId":"u41"},
    "c4725534bb7b49fcbbb3b6702a48c0c2":{
      "scriptId":"u42"},
    "1fa0c3aa6f714f449835cf86f48d6b69":{
      "scriptId":"u43"},
    "d5ddc0c990a7440198504b75550df549":{
      "scriptId":"u44"},
    "b5e8ba95f572451a9fab75fb3a009041":{
      "scriptId":"u45"},
    "2e02f69654184cb7b816ff9fdb4e9175":{
      "scriptId":"u46"},
    "2eeb30e011144430b14328ab39f2ccc8":{
      "scriptId":"u47"},
    "b30816ea3aeb4369a0fa51a358edbf9b":{
      "scriptId":"u48"},
    "b40d2c69f00f420d8a14bf0ce63138bb":{
      "scriptId":"u49"},
    "3b62ec23ef174f4491616595a3ae58a9":{
      "scriptId":"u50"},
    "9f7e447a99304bde9e006ea7eedd6834":{
      "scriptId":"u51"},
    "3b64c2ac03504edfab21553144e9de89":{
      "scriptId":"u52"},
    "5fc467f2f43d4a8884db54ea794785cd":{
      "scriptId":"u53"},
    "70559811add849368b040283d0825fa9":{
      "scriptId":"u54"},
    "223ff94698cf45daa43953d3f1cc2663":{
      "scriptId":"u55",
      "19b3d41a9963435589c9b937e0460da6":{
        "scriptId":"u56"},
      "a6b7fcf8c10d42368892e1102b66fbaf":{
        "scriptId":"u57"},
      "60660e7bbb0d4c4c94d0ddf78e19b0bf":{
        "scriptId":"u58"},
      "9f9baf27fea14a059b9be3da0d1ef825":{
        "scriptId":"u59"},
      "8fcff2c504a34e3484112699bee30a6c":{
        "scriptId":"u60"},
      "b4cd6d1140ec41d6aa60ee66792097c3":{
        "scriptId":"u61"},
      "9651f8f0dead4f38ab1c5a380de305cb":{
        "scriptId":"u62"},
      "02529ae43b9e44c0b41b26d31d899dc5":{
        "scriptId":"u63"},
      "b6a7d2948cea48a4a674ba51bd2b4c02":{
        "scriptId":"u64"},
      "379fa31e4e1440878488b4662b173692":{
        "scriptId":"u65"},
      "d87fbf015e314371872e3894bf8d3b04":{
        "scriptId":"u66"},
      "c88c696597a648eca0d1a0f3fd0f2c59":{
        "scriptId":"u67"},
      "6e57e6a09e6a4c5cb0f4478ad45c4033":{
        "scriptId":"u68"},
      "edce9b88c1b84a97bcf179a7c5ba410a":{
        "scriptId":"u69"},
      "4d6529c5f2854300aa07a1c60ff2a181":{
        "scriptId":"u70"},
      "e11e63f0437e4e35a3583abef588e541":{
        "scriptId":"u71"},
      "4f9f006463574e26aba1e461594f7a34":{
        "scriptId":"u72"},
      "d11ed9864dd44c1c9b0ff5d5f05016b0":{
        "scriptId":"u73"},
      "1799b3c2583c4749b9b1214d15cc1eec":{
        "scriptId":"u74"}},
    "a4525e5eaae74ab68d215bed8e158419":{
      "scriptId":"u75"}}});