<?php
    $_helper = Mage::helper('productattachments');
    $_productAttachmentsCategories = $_helper->getAllParentCategories();
?>


<div id="productattachments-wrapper">
    <div class="attachment_sections_box">
        <div class="headbar">
            <p><?php echo $_helper->__('Downloads'); ?></p>
        </div>
        <ul>
            <?php
                $counter = 1;
            ?>
            <?php foreach ($_productAttachmentsCategories as $category): ?>
               
            <li <?php if ($counter == 3):?>class="last" <?php $counter = 0;?> <?php endif; ?> >
                    <div class="box">
                        <div class="name">
                            <p><a href="<?php echo Mage::getUrl('*/*/view', array('u' => $category->getCategoryUrlKey())) ?>"><?php echo $category->getCategoryName(); ?></a> <?php echo $_helper->__('(%s)', $this->countSubCategories($category->getCategoryId())) ?></p>

                            <?php if ($_helper->getSubCategories($category->getCategoryId())->count() > 0): ?>
                                <?php
                                $sub = $_helper->getSubCategories($category->getCategoryId());
                                ?>	
                                <ul>
                                    <?php foreach ($sub as $item): ?>
                                        <li><a href="<?php echo Mage::getUrl('*/*/view', array('u' => $item->getCategoryUrlKey())) ?>"><?php echo $item->getCategoryName(); ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else: ?>
                                <p><?php echo $_helper->__('Nothing to display.') ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
                 <?php $counter++; ?>
            <?php endforeach; ?>
        </ul>
        <div class="clear"></div>

    </div>
</div>
