$axure.loadCurrentPage({
  "url":"输入物流与发票信息.html",
  "generationDate":new Date(1452351349566.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"09284fdbe42b480eae7ac031d7b54a76",
    "type":"Axure:Page",
    "name":"输入物流与发票信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9b2e99ae9eac401482ea2023979f47eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":468},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b697aae6154fe19884b599ecfd8c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":468},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入物流与发票信息/u0.png"}},
{
          "id":"c2f0fe9016bc44a9b0a7d4bba44f1bea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":531.5},
            "size":{
              "width":25,
              "height":25},
            "limbo":true,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"192955d412534d90b766034763252393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":531.5},
                "size":{
                  "width":25,
                  "height":25},
                "limbo":true,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u13.png"}},
{
          "id":"ede6d85da4b24e4b8e7f6ff39bccf5b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":103,
              "y":532},
            "size":{
              "width":27,
              "height":26},
            "limbo":true,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ad84b4f0eb414b9174d02184480017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":103,
                  "y":532},
                "size":{
                  "width":27,
                  "height":26},
                "limbo":true,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"1d82b0d436d4437c8764df2222c65c0f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":534},
            "size":{
              "width":24,
              "height":24},
            "limbo":true,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e5d3904183a47259e7b6e20bceb3b17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":534},
                "size":{
                  "width":24,
                  "height":24},
                "limbo":true,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u17.png"}},
{
          "id":"da1f9f45250346acb6a71d47ed3b2c51",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":264,
              "y":534},
            "size":{
              "width":25,
              "height":25},
            "limbo":true,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34dd81115b8e4873b7cefd3f91a634b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":264,
                  "y":534},
                "size":{
                  "width":25,
                  "height":25},
                "limbo":true,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u19.png"}},
{
          "id":"046ba95e566c44b7bb57684828e530af",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"d4dc7474b0d74a8cb8408f79281d3a01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":29,
              "y":141},
            "size":{
              "width":376,
              "height":529},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"824e450c0f3c4a028c0b851ba4b30090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":29,
                  "y":141},
                "size":{
                  "width":376,
                  "height":529},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/输入物流与发票信息/u35.png"}},
{
          "id":"619672c0a9fe451c979ffbe1979e261f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":710},
            "size":{
              "width":114,
              "height":57}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付",
                      "target":{
                        "targetType":"page",
                        "url":"支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3fad059c097547b18e266857f155f02b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"76635873ed5d45c4a1627735b63fa348"},
{
          "id":"aeff3136cb804164b418c53f8084fbb4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":213,
              "y":129},
            "size":{
              "width":85,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-选择印章类型-采购/u56_line.png"}},
{
          "id":"c59cc83d5c2a4b8189335367f50ce0dc",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":237,
              "y":671},
            "size":{
              "width":150,
              "height":40},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"947ddf02b45a4d09ba037b88bda0a6e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":237,
                  "y":671},
                "size":{
                  "width":150,
                  "height":40},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 支付",
                      "target":{
                        "targetType":"page",
                        "url":"支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34.png",
            "mouseDown~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34_mouseDown.png"}},
{
          "id":"c4112680ee6c46be9ca372c0149904c9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":141},
            "size":{
              "width":330,
              "height":89}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置收货地址",
                      "target":{
                        "targetType":"page",
                        "url":"设置收货地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "76635873ed5d45c4a1627735b63fa348":{
      "packageId":"76635873ed5d45c4a1627735b63fa348",
      "type":"Axure:Master",
      "name":"操作导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"19b3d41a9963435589c9b937e0460da6",
            "label":"操作导航状态",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":104},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"fd28231fa9814070a09aff6ceca23bbf",
                "label":"State4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"a6b7fcf8c10d42368892e1102b66fbaf",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":277,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"60660e7bbb0d4c4c94d0ddf78e19b0bf",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":277,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u38.png",
                      "selected~":"images/首页-选择印章类型-采购/u38_selected.png"}},
{
                    "id":"9f9baf27fea14a059b9be3da0d1ef825",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "location":{
                        "x":187,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8fcff2c504a34e3484112699bee30a6c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "location":{
                            "x":187,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"b4cd6d1140ec41d6aa60ee66792097c3",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":180,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9651f8f0dead4f38ab1c5a380de305cb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":180,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"02529ae43b9e44c0b41b26d31d899dc5",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":97,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b6a7d2948cea48a4a674ba51bd2b4c02",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":97,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"379fa31e4e1440878488b4662b173692",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":90,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d87fbf015e314371872e3894bf8d3b04",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":90,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"c88c696597a648eca0d1a0f3fd0f2c59",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":7,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6e57e6a09e6a4c5cb0f4478ad45c4033",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":7,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"edce9b88c1b84a97bcf179a7c5ba410a",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4d6529c5f2854300aa07a1c60ff2a181",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}}]}]},
{
            "id":"e11e63f0437e4e35a3583abef588e541",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":27,
                "y":103},
              "size":{
                "width":91,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4f9f006463574e26aba1e461594f7a34",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":128,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 印章信息输入 | 一级注册建筑师",
                        "target":{
                          "targetType":"page",
                          "url":"印章信息输入___一级注册建筑师.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d11ed9864dd44c1c9b0ff5d5f05016b0",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":218,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 输入物流与发票信息",
                        "target":{
                          "targetType":"page",
                          "url":"输入物流与发票信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1799b3c2583c4749b9b1214d15cc1eec",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":104},
              "size":{
                "width":94,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付",
                        "target":{
                          "targetType":"page",
                          "url":"支付.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "9b2e99ae9eac401482ea2023979f47eb":{
      "scriptId":"u0"},
    "92b697aae6154fe19884b599ecfd8c45":{
      "scriptId":"u1"},
    "c2f0fe9016bc44a9b0a7d4bba44f1bea":{
      "scriptId":"u2"},
    "192955d412534d90b766034763252393":{
      "scriptId":"u3"},
    "ede6d85da4b24e4b8e7f6ff39bccf5b4":{
      "scriptId":"u4"},
    "83ad84b4f0eb414b9174d02184480017":{
      "scriptId":"u5"},
    "1d82b0d436d4437c8764df2222c65c0f":{
      "scriptId":"u6"},
    "9e5d3904183a47259e7b6e20bceb3b17":{
      "scriptId":"u7"},
    "da1f9f45250346acb6a71d47ed3b2c51":{
      "scriptId":"u8"},
    "34dd81115b8e4873b7cefd3f91a634b7":{
      "scriptId":"u9"},
    "046ba95e566c44b7bb57684828e530af":{
      "scriptId":"u10",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u11"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u12"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u13"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u14"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u15"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u16"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u17"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u18"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u19"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u20"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u21"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u22"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u23"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u24"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u25"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u26"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u27"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u28"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u29"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u30"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u31"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u32"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u33"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u34"}},
    "d4dc7474b0d74a8cb8408f79281d3a01":{
      "scriptId":"u35"},
    "824e450c0f3c4a028c0b851ba4b30090":{
      "scriptId":"u36"},
    "619672c0a9fe451c979ffbe1979e261f":{
      "scriptId":"u37"},
    "3fad059c097547b18e266857f155f02b":{
      "scriptId":"u38",
      "19b3d41a9963435589c9b937e0460da6":{
        "scriptId":"u39"},
      "a6b7fcf8c10d42368892e1102b66fbaf":{
        "scriptId":"u40"},
      "60660e7bbb0d4c4c94d0ddf78e19b0bf":{
        "scriptId":"u41"},
      "9f9baf27fea14a059b9be3da0d1ef825":{
        "scriptId":"u42"},
      "8fcff2c504a34e3484112699bee30a6c":{
        "scriptId":"u43"},
      "b4cd6d1140ec41d6aa60ee66792097c3":{
        "scriptId":"u44"},
      "9651f8f0dead4f38ab1c5a380de305cb":{
        "scriptId":"u45"},
      "02529ae43b9e44c0b41b26d31d899dc5":{
        "scriptId":"u46"},
      "b6a7d2948cea48a4a674ba51bd2b4c02":{
        "scriptId":"u47"},
      "379fa31e4e1440878488b4662b173692":{
        "scriptId":"u48"},
      "d87fbf015e314371872e3894bf8d3b04":{
        "scriptId":"u49"},
      "c88c696597a648eca0d1a0f3fd0f2c59":{
        "scriptId":"u50"},
      "6e57e6a09e6a4c5cb0f4478ad45c4033":{
        "scriptId":"u51"},
      "edce9b88c1b84a97bcf179a7c5ba410a":{
        "scriptId":"u52"},
      "4d6529c5f2854300aa07a1c60ff2a181":{
        "scriptId":"u53"},
      "e11e63f0437e4e35a3583abef588e541":{
        "scriptId":"u54"},
      "4f9f006463574e26aba1e461594f7a34":{
        "scriptId":"u55"},
      "d11ed9864dd44c1c9b0ff5d5f05016b0":{
        "scriptId":"u56"},
      "1799b3c2583c4749b9b1214d15cc1eec":{
        "scriptId":"u57"}},
    "aeff3136cb804164b418c53f8084fbb4":{
      "scriptId":"u58"},
    "c59cc83d5c2a4b8189335367f50ce0dc":{
      "scriptId":"u59"},
    "947ddf02b45a4d09ba037b88bda0a6e4":{
      "scriptId":"u60"},
    "c4112680ee6c46be9ca372c0149904c9":{
      "scriptId":"u61"}}});