$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1452351348733.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"890926ab52ff4e13a8809e05822cf3e0",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd5054186bac48f3866e8a4226c822f3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"61f630c662c94919801554fdce1efa56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":65,
              "y":158},
            "size":{
              "width":310,
              "height":366},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7d10cde1a1e400baf77dc4262babf93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":65,
                  "y":158},
                "size":{
                  "width":310,
                  "height":366},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u25.png"}},
{
          "id":"cf4ebb8e88224a4fb77c8193784b36b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "location":{
              "x":220,
              "y":463},
            "size":{
              "width":135,
              "height":45},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC33},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e10b200975142fe8c4e35efe57a17ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "location":{
                  "x":220,
                  "y":463},
                "size":{
                  "width":135,
                  "height":45},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC33},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                      "target":{
                        "targetType":"page",
                        "url":"首页-选择印章类型-采购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u27.png"}},
{
          "id":"8d72e45f00b440f4a0f5975edbdf66f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"24px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":88,
              "y":167},
            "size":{
              "width":150,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2132e5866b97416f87ada7c99f76c440",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"24px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":167},
                "size":{
                  "width":150,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bd6a7bb20d44149ac1e137e5cf89ab8",
          "label":"验证框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":88,
              "y":380},
            "size":{
              "width":135,
              "height":43}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入验证码"},
{
          "id":"08ee9317453f4ef9941d81ea2cf0274b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":88,
              "y":433},
            "size":{
              "width":100,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c110d188cea142f59082d3a47120bb4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":433},
                "size":{
                  "width":100,
                  "height":18}},
              "adaptiveStyles":{
}}]},
{
          "id":"7e139b8a9fbd4b5ea3052d784be55366",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":88,
              "y":354},
            "size":{
              "width":150,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac12a38b800a46c08ec6d832ad4b24cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":354},
                "size":{
                  "width":150,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71f8a093cad54c7f8f912bbdb8744a1e",
          "label":"验证码",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"bold",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":233,
              "y":380},
            "size":{
              "width":79,
              "height":43},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c388243435c44966acadde885a6546ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"bold",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":233,
                  "y":380},
                "size":{
                  "width":79,
                  "height":43},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 验证码 = &quot;E G 9 D&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c388243435c44966acadde885a6546ca"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"font-size:13px;text-align:center;line-height:normal;\"><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">E</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">G</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">9</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">D</span></p>",
                                "localVariables":{
},
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":false}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/验证码_u36.png"}},
{
          "id":"56d518336cd24246aadbf282ea110b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":322,
              "y":407},
            "size":{
              "width":33,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68cec9f33bfb4821ba0b8293b97dd166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":322,
                  "y":407},
                "size":{
                  "width":33,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 验证码 = &quot;7 9 R H&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c388243435c44966acadde885a6546ca"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"font-size:13px;text-align:center;line-height:normal;\"><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">7</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">9</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">R</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">&nbsp;</span><span style=\"font-family:'Applied Font Bold', 'Applied Font';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">H</span></p>",
                                "localVariables":{
},
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":false}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97ee95f3a0cb4be7bdeb08b40f4d9207",
          "label":"密码输入框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":88,
              "y":276},
            "size":{
              "width":240,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入登录密码"},
{
          "id":"aca488e2ecde46a99c413fb5e095b92a",
          "label":"账号输入框",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":88,
              "y":208},
            "size":{
              "width":240,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入登录账号"},
{
          "id":"c676f8a502da4fc985526f7be52717ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":64,
              "y":524},
            "size":{
              "width":311,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32a33e8006bf440b980de5697d04b29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":64,
                  "y":524},
                "size":{
                  "width":311,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u42.png"}},
{
          "id":"c7da23ae871f496a94a4845e94cf346b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "location":{
              "x":76,
              "y":464},
            "size":{
              "width":135,
              "height":45},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC33},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5b1307d61f4b6a9c9dee27b631b789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "location":{
                  "x":76,
                  "y":464},
                "size":{
                  "width":135,
                  "height":45},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC33},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/登录/u27.png"}}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "dd5054186bac48f3866e8a4226c822f3":{
      "scriptId":"u0",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u1"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u2"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u3"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u4"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u5"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u6"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u7"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u8"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u9"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u10"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u11"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u12"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u13"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u14"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u15"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u16"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u17"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u18"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u19"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u20"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u21"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u22"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u23"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u24"}},
    "61f630c662c94919801554fdce1efa56":{
      "scriptId":"u25"},
    "e7d10cde1a1e400baf77dc4262babf93":{
      "scriptId":"u26"},
    "cf4ebb8e88224a4fb77c8193784b36b7":{
      "scriptId":"u27"},
    "9e10b200975142fe8c4e35efe57a17ef":{
      "scriptId":"u28"},
    "8d72e45f00b440f4a0f5975edbdf66f3":{
      "scriptId":"u29"},
    "2132e5866b97416f87ada7c99f76c440":{
      "scriptId":"u30"},
    "6bd6a7bb20d44149ac1e137e5cf89ab8":{
      "scriptId":"u31"},
    "08ee9317453f4ef9941d81ea2cf0274b":{
      "scriptId":"u32"},
    "c110d188cea142f59082d3a47120bb4b":{
      "scriptId":"u33"},
    "7e139b8a9fbd4b5ea3052d784be55366":{
      "scriptId":"u34"},
    "ac12a38b800a46c08ec6d832ad4b24cf":{
      "scriptId":"u35"},
    "71f8a093cad54c7f8f912bbdb8744a1e":{
      "scriptId":"u36"},
    "c388243435c44966acadde885a6546ca":{
      "scriptId":"u37"},
    "56d518336cd24246aadbf282ea110b7e":{
      "scriptId":"u38"},
    "68cec9f33bfb4821ba0b8293b97dd166":{
      "scriptId":"u39"},
    "97ee95f3a0cb4be7bdeb08b40f4d9207":{
      "scriptId":"u40"},
    "aca488e2ecde46a99c413fb5e095b92a":{
      "scriptId":"u41"},
    "c676f8a502da4fc985526f7be52717ab":{
      "scriptId":"u42"},
    "32a33e8006bf440b980de5697d04b29e":{
      "scriptId":"u43"},
    "c7da23ae871f496a94a4845e94cf346b":{
      "scriptId":"u44"},
    "7e5b1307d61f4b6a9c9dee27b631b789":{
      "scriptId":"u45"}}});