$axure.loadCurrentPage({
  "url":"印章信息输入___一级注册建筑师.html",
  "generationDate":new Date(1452351348941.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"sfz",
"sfz_n"],
  "page":{
    "packageId":"5a7295422b6e4c23a3cc62bb0d8b9979",
    "type":"Axure:Page",
    "name":"印章信息输入 | 一级注册建筑师",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"598bb0dc55e4443db6e131d153792e7c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5ac57e3875a541499e856f1472c2dae2"},
{
          "id":"4e13ae2c426340898d668f71b8a98f2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":44,
              "y":262},
            "size":{
              "width":336,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e4274bd9a5a4ec197a3001e89618159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":44,
                  "y":262},
                "size":{
                  "width":336,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/印章信息输入___一级注册建筑师/u25.png"}},
{
          "id":"61ce7007a16b4c8aa07e87fdd807df73",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":45,
              "y":349},
            "size":{
              "width":347,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feaaad56be42495091daade0f51111e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be84ed3819864c72b1a6f944598982ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"c44e25bdf29d4965b399e989eb2e3a02",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":0},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc9dcac7fb7648e6b4a34769d7ff9d82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":0},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"68084c3a1179454483ba69efa8130c4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33936ea3716249068cebab71cbba4ce4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"89acdc037a614d00aaa4796c86c57c98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":90},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7ff51238971475e99cabd814d1f1b7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":90},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"62c4f8ad0f0e40e2b986d7ebaf919cde",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52e03ff590ad43fab925977f074d9eea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"d86714a2a9c1482899448da364057cfc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":60},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b546fa59ec0423fa60ada0f943fc22b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":60},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}},
{
              "id":"0ca70fe77a1a4f78b814d78a6344aa2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":135,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e4862cd860f415493d66881aaadcb99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":135,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u28.png"}},
{
              "id":"1b24151ea15b4e19aa01a588f8b5a3e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "verticalAlignment":"middle",
                "location":{
                  "x":135,
                  "y":30},
                "size":{
                  "width":212,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d723d7a60e1a43a4b44e2af5beb8628b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":135,
                      "y":30},
                    "size":{
                      "width":212,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/印章信息输入___一级注册建筑师/u30.png"}}]},
{
          "id":"959cefa1d68b44919086f0ff4b4ee96c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "location":{
              "x":39,
              "y":300},
            "size":{
              "width":357,
              "height":40},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e4d6dd3aeb4d4cbcf1a00d88464405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "location":{
                  "x":39,
                  "y":300},
                "size":{
                  "width":357,
                  "height":40},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/印章信息输入___一级注册建筑师/u44.png"}},
{
          "id":"a05d27859f9e4d06814c2324a92b605a",
          "label":"ButtonBigSecondary",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"700",
            "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
            "stateStyles":{
              "mouseDown":{
                "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
            "location":{
              "x":230,
              "y":469},
            "size":{
              "width":150,
              "height":40},
            "borderWidth":"3",
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f6730b59a2843ae8bdcf6d127cb8af4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"700",
                "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                "stateStyles":{
                  "mouseDown":{
                    "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"}},
                "location":{
                  "x":230,
                  "y":469},
                "size":{
                  "width":150,
                  "height":40},
                "borderWidth":"3",
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 保存了1个印章",
                      "target":{
                        "targetType":"page",
                        "url":"保存了1个印章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34.png",
            "mouseDown~":"images/首页-选择印章类型-采购/buttonbigsecondary_u34_mouseDown.png"}},
{
          "id":"1a2b971386354a9e83ed1b0cb46f6f60",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"353289f9cf554f2ba53477ede4c6811d"},
{
          "id":"affed6137dac4d679f83107759db1fba",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":351},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4bc8f07c0c474a659327a2757161681f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":383},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4319d180ffe649e4af2a65334353cae5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":412},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"054de8e8edbc4645a0a99c202a9b2f05",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":441},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a5b201912d964194b6626837f479e63c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"5a3c95f56a004e728a6af28b9a52cee6"},
{
          "id":"51bb2be340a644c38e31ad4dc3f60171",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"76635873ed5d45c4a1627735b63fa348"},
{
          "id":"9a50b08c8ed344f4885e11ac78b12182",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":129},
            "size":{
              "width":85,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/首页-选择印章类型-采购/u56_line.png"}}]}},
  "masters":{
    "5ac57e3875a541499e856f1472c2dae2":{
      "packageId":"5ac57e3875a541499e856f1472c2dae2",
      "type":"Axure:Master",
      "name":"框架",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af87fae6a0a74398931612b191b821f3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":430,
                "height":860}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b6f49fd634b54adda0ed451509c2ba9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":430,
                    "height":860}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u1.jpg"}},
{
            "id":"2ff451c47aa94c75af9d0cc4f2efebdf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":28,
                "y":101},
              "size":{
                "width":377,
                "height":667},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d2600f4ee7842799e35068152872707",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":28,
                    "y":101},
                  "size":{
                    "width":377,
                    "height":667},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u3.png"}},
{
            "id":"982a0caa453c4349a710bdc8923f2ec9",
            "label":"SegmentedBtn1",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":30,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"9"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c40b2489646f4089bceaa1b99159906f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":30,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"9"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn1 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["982a0caa453c4349a710bdc8923f2ec9"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn1_u5.png",
              "selected~":"images/注册/segmentedbtn1_u5_selected.png",
              "mouseDown~":"images/注册/segmentedbtn1_u5_mouseDown.png"}},
{
            "id":"ca606540c7a846778012278822496bc0",
            "label":"SegmentedBtn4",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":310,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2",
              "cornerRadiusTopLeft":"10"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ad1c18a653d421f8d886d38a931c94e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":310,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2",
                  "cornerRadiusTopLeft":"10"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn4 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["ca606540c7a846778012278822496bc0"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn4_u7.png",
              "selected~":"images/注册/segmentedbtn4_u7_selected.png",
              "mouseDown~":"images/注册/segmentedbtn4_u7_mouseDown.png"}},
{
            "id":"7082ecdedc314d599782ef451a711550",
            "label":"SegmentedBtn2",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":123,
                "y":717},
              "size":{
                "width":94,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0498ddca854148b1a52d0ade07bcfd8d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":123,
                    "y":717},
                  "size":{
                    "width":94,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn2 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["7082ecdedc314d599782ef451a711550"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn2_u9.png",
              "selected~":"images/注册/segmentedbtn2_u9_selected.png",
              "mouseDown~":"images/注册/segmentedbtn2_u9_mouseDown.png"}},
{
            "id":"1d3f123edb87444580e55a2f2d20ca4d",
            "label":"SegmentedBtn3",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"14px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF009DDA,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "stateStyles":{
                "mouseDown":{
                  "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                "selected":{
                  "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":217,
                "y":717},
              "size":{
                "width":93,
                "height":50},
              "borderWidth":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5817be31d0b4083ae3b1cec8dbfc883",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF009DDA,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "stateStyles":{
                    "mouseDown":{
                      "baseStyle":"4df78fa7fa904ef294afbee20e1f20c7"},
                    "selected":{
                      "baseStyle":"d29cc72b6c974b5ea46614e4789869b0"}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":217,
                    "y":717},
                  "size":{
                    "width":93,
                    "height":50},
                  "borderWidth":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 被选中的 SegmentedBtn3 = &quot;true&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetCheckState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["1d3f123edb87444580e55a2f2d20ca4d"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"true",
                                  "stos":[]}]}]}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/注册/segmentedbtn3_u11.png",
              "selected~":"images/注册/segmentedbtn3_u11_selected.png",
              "mouseDown~":"images/注册/segmentedbtn3_u11_mouseDown.png"}},
{
            "id":"5037222bf3154c82aa7358cd85f16a75",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":38,
                "y":726},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3d3826989c7a4660a85dd603af462674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":38,
                    "y":726},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u13.png"}},
{
            "id":"a2f8e7732cf34af69514d94d1546d9a6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":129,
                "y":728},
              "size":{
                "width":27,
                "height":26},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24c9a430410941fab2ab2f7c34dfa2d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":129,
                    "y":728},
                  "size":{
                    "width":27,
                    "height":26},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u15.png"}},
{
            "id":"85c29e1b997847f5b6575373e5ae869a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":225,
                "y":730},
              "size":{
                "width":24,
                "height":24},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"462aa2697df649d981d1b82689e5d66c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":225,
                    "y":730},
                  "size":{
                    "width":24,
                    "height":24},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u17.png"}},
{
            "id":"be26c11cc0fd4f09a6c7b9ce1bb5a11c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":316,
                "y":729},
              "size":{
                "width":25,
                "height":25},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59da1bbdd7224ddbb965479b230e8f56",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":316,
                    "y":729},
                  "size":{
                    "width":25,
                    "height":25},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/注册/u19.png"}},
{
            "id":"a8a8580679704de088fb45c762c7243d",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":35,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9ec0ea68ec194a9ca943c1febb4ea7bc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":125,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物车",
                        "target":{
                          "targetType":"page",
                          "url":"购物车.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1fd6398a64c74a79aabb707ffcdaa910",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":216,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2038c5bb57fd4351a243f106d1300dfc",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":308,
                "y":717},
              "size":{
                "width":91,
                "height":50}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 客户留言答疑",
                        "target":{
                          "targetType":"page",
                          "url":"客户留言答疑.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "353289f9cf554f2ba53477ede4c6811d":{
      "packageId":"353289f9cf554f2ba53477ede4c6811d",
      "type":"Axure:Master",
      "name":"宣传banner1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa1d6d34f9864f448bcd305ad2ae533c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF76A9E0,
                "opacity":1},
              "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":29,
                "y":142},
              "size":{
                "width":375,
                "height":61},
              "borderWidth":"3"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b0511df5f8fd4f5197debbcca001b304",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF76A9E0,
                    "opacity":1},
                  "baseStyle":"fbb5bf0f859d426aac632ca8fd1f3908",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":29,
                    "y":142},
                  "size":{
                    "width":375,
                    "height":61},
                  "borderWidth":"3"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-选择印章类型-采购/u32.png"}}]}},
    "5a3c95f56a004e728a6af28b9a52cee6":{
      "packageId":"5a3c95f56a004e728a6af28b9a52cee6",
      "type":"Axure:Master",
      "name":"资格搜索",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"86568f3192454caab77b16d57346aeca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":44,
                "y":219},
              "size":{
                "width":336,
                "height":33},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8abe167327494e0c9369daca10994c32",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":44,
                    "y":219},
                  "size":{
                    "width":336,
                    "height":33},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/印章信息输入___一级注册建筑师/u56.png"}},
{
            "id":"c4da1ca5e5be44efacacf45daf52f97f",
            "label":"搜索框",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "stateStyles":{
                "hint":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1}}},
              "location":{
                "x":54,
                "y":223},
              "size":{
                "width":219,
                "height":25}},
            "adaptiveStyles":{
},
            "placeholderText":"请输入关键字搜索"},
{
            "id":"9c0dcc6193a144c599278bbd96ca2e5a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":283,
                "y":223},
              "size":{
                "width":90,
                "height":25},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e98bd3b1d8f4795ada477eb2ff2a055",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":283,
                    "y":223},
                  "size":{
                    "width":90,
                    "height":25},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/印章信息输入___一级注册建筑师/u59.png"}},
{
            "id":"cd9f94b5dcba4e40823c6c39dc80def2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":297,
                "y":225},
              "size":{
                "width":22,
                "height":22},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1751a5917ac54c7187e0013ccf26286e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":297,
                    "y":225},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/印章信息输入___一级注册建筑师/u61.png"}},
{
            "id":"3e381e75d6ad428f9d4ea1843f3a4aa9",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":283,
                "y":216},
              "size":{
                "width":97,
                "height":36}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 快速注册资料检索",
                        "target":{
                          "targetType":"page",
                          "url":"快速注册资料检索.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "76635873ed5d45c4a1627735b63fa348":{
      "packageId":"76635873ed5d45c4a1627735b63fa348",
      "type":"Axure:Master",
      "name":"操作导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"19b3d41a9963435589c9b937e0460da6",
            "label":"操作导航状态",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":29,
                "y":104},
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"fd28231fa9814070a09aff6ceca23bbf",
                "label":"State4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"a6b7fcf8c10d42368892e1102b66fbaf",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":277,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"60660e7bbb0d4c4c94d0ddf78e19b0bf",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":277,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u38.png",
                      "selected~":"images/首页-选择印章类型-采购/u38_selected.png"}},
{
                    "id":"9f9baf27fea14a059b9be3da0d1ef825",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "location":{
                        "x":187,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8fcff2c504a34e3484112699bee30a6c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "location":{
                            "x":187,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"b4cd6d1140ec41d6aa60ee66792097c3",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":180,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9651f8f0dead4f38ab1c5a380de305cb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":180,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"02529ae43b9e44c0b41b26d31d899dc5",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":97,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"b6a7d2948cea48a4a674ba51bd2b4c02",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":97,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"379fa31e4e1440878488b4662b173692",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "location":{
                        "x":90,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d87fbf015e314371872e3894bf8d3b04",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "location":{
                            "x":90,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}},
{
                    "id":"c88c696597a648eca0d1a0f3fd0f2c59",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "location":{
                        "x":7,
                        "y":0},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6e57e6a09e6a4c5cb0f4478ad45c4033",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "location":{
                            "x":7,
                            "y":0},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u40.png"}},
{
                    "id":"edce9b88c1b84a97bcf179a7c5ba410a",
                    "label":"",
                    "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "fontSize":"11px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF999999,
                        "opacity":1},
                      "stateStyles":{
                        "selected":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF009DDA},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF009DDA}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4},
                      "size":{
                        "width":98,
                        "height":30},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4d6529c5f2854300aa07a1c60ff2a181",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"19b3d41a9963435589c9b937e0460da6",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Applied Font Regular', 'Applied Font'",
                          "fontSize":"11px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF999999,
                            "opacity":1},
                          "stateStyles":{
                            "selected":{
                              "fontName":"'Applied Font Regular', 'Applied Font'",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF009DDA},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFF009DDA}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4},
                          "size":{
                            "width":98,
                            "height":30},
                          "borderWidth":"2",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页-选择印章类型-采购/u42.png",
                      "selected~":"images/首页-选择印章类型-采购/u42_selected.png"}}]}]},
{
            "id":"e11e63f0437e4e35a3583abef588e541",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":27,
                "y":103},
              "size":{
                "width":91,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-选择印章类型-采购",
                        "target":{
                          "targetType":"page",
                          "url":"首页-选择印章类型-采购.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4f9f006463574e26aba1e461594f7a34",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":128,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 印章信息输入 | 一级注册建筑师",
                        "target":{
                          "targetType":"page",
                          "url":"印章信息输入___一级注册建筑师.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d11ed9864dd44c1c9b0ff5d5f05016b0",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":218,
                "y":103},
              "size":{
                "width":90,
                "height":30}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 输入物流与发票信息",
                        "target":{
                          "targetType":"page",
                          "url":"输入物流与发票信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1799b3c2583c4749b9b1214d15cc1eec",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":309,
                "y":104},
              "size":{
                "width":94,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"设置 面板状态为",
                        "panelsToStates":[]},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 支付",
                        "target":{
                          "targetType":"page",
                          "url":"支付.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "598bb0dc55e4443db6e131d153792e7c":{
      "scriptId":"u0",
      "af87fae6a0a74398931612b191b821f3":{
        "scriptId":"u1"},
      "b6f49fd634b54adda0ed451509c2ba9d":{
        "scriptId":"u2"},
      "2ff451c47aa94c75af9d0cc4f2efebdf":{
        "scriptId":"u3"},
      "8d2600f4ee7842799e35068152872707":{
        "scriptId":"u4"},
      "982a0caa453c4349a710bdc8923f2ec9":{
        "scriptId":"u5"},
      "c40b2489646f4089bceaa1b99159906f":{
        "scriptId":"u6"},
      "ca606540c7a846778012278822496bc0":{
        "scriptId":"u7"},
      "1ad1c18a653d421f8d886d38a931c94e":{
        "scriptId":"u8"},
      "7082ecdedc314d599782ef451a711550":{
        "scriptId":"u9"},
      "0498ddca854148b1a52d0ade07bcfd8d":{
        "scriptId":"u10"},
      "1d3f123edb87444580e55a2f2d20ca4d":{
        "scriptId":"u11"},
      "a5817be31d0b4083ae3b1cec8dbfc883":{
        "scriptId":"u12"},
      "5037222bf3154c82aa7358cd85f16a75":{
        "scriptId":"u13"},
      "3d3826989c7a4660a85dd603af462674":{
        "scriptId":"u14"},
      "a2f8e7732cf34af69514d94d1546d9a6":{
        "scriptId":"u15"},
      "24c9a430410941fab2ab2f7c34dfa2d9":{
        "scriptId":"u16"},
      "85c29e1b997847f5b6575373e5ae869a":{
        "scriptId":"u17"},
      "462aa2697df649d981d1b82689e5d66c":{
        "scriptId":"u18"},
      "be26c11cc0fd4f09a6c7b9ce1bb5a11c":{
        "scriptId":"u19"},
      "59da1bbdd7224ddbb965479b230e8f56":{
        "scriptId":"u20"},
      "a8a8580679704de088fb45c762c7243d":{
        "scriptId":"u21"},
      "9ec0ea68ec194a9ca943c1febb4ea7bc":{
        "scriptId":"u22"},
      "1fd6398a64c74a79aabb707ffcdaa910":{
        "scriptId":"u23"},
      "2038c5bb57fd4351a243f106d1300dfc":{
        "scriptId":"u24"}},
    "4e13ae2c426340898d668f71b8a98f2a":{
      "scriptId":"u25"},
    "1e4274bd9a5a4ec197a3001e89618159":{
      "scriptId":"u26"},
    "61ce7007a16b4c8aa07e87fdd807df73":{
      "scriptId":"u27"},
    "feaaad56be42495091daade0f51111e2":{
      "scriptId":"u28"},
    "be84ed3819864c72b1a6f944598982ce":{
      "scriptId":"u29"},
    "c44e25bdf29d4965b399e989eb2e3a02":{
      "scriptId":"u30"},
    "dc9dcac7fb7648e6b4a34769d7ff9d82":{
      "scriptId":"u31"},
    "0ca70fe77a1a4f78b814d78a6344aa2d":{
      "scriptId":"u32"},
    "7e4862cd860f415493d66881aaadcb99":{
      "scriptId":"u33"},
    "1b24151ea15b4e19aa01a588f8b5a3e8":{
      "scriptId":"u34"},
    "d723d7a60e1a43a4b44e2af5beb8628b":{
      "scriptId":"u35"},
    "62c4f8ad0f0e40e2b986d7ebaf919cde":{
      "scriptId":"u36"},
    "52e03ff590ad43fab925977f074d9eea":{
      "scriptId":"u37"},
    "d86714a2a9c1482899448da364057cfc":{
      "scriptId":"u38"},
    "0b546fa59ec0423fa60ada0f943fc22b":{
      "scriptId":"u39"},
    "68084c3a1179454483ba69efa8130c4c":{
      "scriptId":"u40"},
    "33936ea3716249068cebab71cbba4ce4":{
      "scriptId":"u41"},
    "89acdc037a614d00aaa4796c86c57c98":{
      "scriptId":"u42"},
    "a7ff51238971475e99cabd814d1f1b7b":{
      "scriptId":"u43"},
    "959cefa1d68b44919086f0ff4b4ee96c":{
      "scriptId":"u44"},
    "b5e4d6dd3aeb4d4cbcf1a00d88464405":{
      "scriptId":"u45"},
    "a05d27859f9e4d06814c2324a92b605a":{
      "scriptId":"u46"},
    "8f6730b59a2843ae8bdcf6d127cb8af4":{
      "scriptId":"u47"},
    "1a2b971386354a9e83ed1b0cb46f6f60":{
      "scriptId":"u48",
      "aa1d6d34f9864f448bcd305ad2ae533c":{
        "scriptId":"u49"},
      "b0511df5f8fd4f5197debbcca001b304":{
        "scriptId":"u50"}},
    "affed6137dac4d679f83107759db1fba":{
      "scriptId":"u51"},
    "4bc8f07c0c474a659327a2757161681f":{
      "scriptId":"u52"},
    "4319d180ffe649e4af2a65334353cae5":{
      "scriptId":"u53"},
    "054de8e8edbc4645a0a99c202a9b2f05":{
      "scriptId":"u54"},
    "a5b201912d964194b6626837f479e63c":{
      "scriptId":"u55",
      "86568f3192454caab77b16d57346aeca":{
        "scriptId":"u56"},
      "8abe167327494e0c9369daca10994c32":{
        "scriptId":"u57"},
      "c4da1ca5e5be44efacacf45daf52f97f":{
        "scriptId":"u58"},
      "9c0dcc6193a144c599278bbd96ca2e5a":{
        "scriptId":"u59"},
      "0e98bd3b1d8f4795ada477eb2ff2a055":{
        "scriptId":"u60"},
      "cd9f94b5dcba4e40823c6c39dc80def2":{
        "scriptId":"u61"},
      "1751a5917ac54c7187e0013ccf26286e":{
        "scriptId":"u62"},
      "3e381e75d6ad428f9d4ea1843f3a4aa9":{
        "scriptId":"u63"}},
    "51bb2be340a644c38e31ad4dc3f60171":{
      "scriptId":"u64",
      "19b3d41a9963435589c9b937e0460da6":{
        "scriptId":"u65"},
      "a6b7fcf8c10d42368892e1102b66fbaf":{
        "scriptId":"u66"},
      "60660e7bbb0d4c4c94d0ddf78e19b0bf":{
        "scriptId":"u67"},
      "9f9baf27fea14a059b9be3da0d1ef825":{
        "scriptId":"u68"},
      "8fcff2c504a34e3484112699bee30a6c":{
        "scriptId":"u69"},
      "b4cd6d1140ec41d6aa60ee66792097c3":{
        "scriptId":"u70"},
      "9651f8f0dead4f38ab1c5a380de305cb":{
        "scriptId":"u71"},
      "02529ae43b9e44c0b41b26d31d899dc5":{
        "scriptId":"u72"},
      "b6a7d2948cea48a4a674ba51bd2b4c02":{
        "scriptId":"u73"},
      "379fa31e4e1440878488b4662b173692":{
        "scriptId":"u74"},
      "d87fbf015e314371872e3894bf8d3b04":{
        "scriptId":"u75"},
      "c88c696597a648eca0d1a0f3fd0f2c59":{
        "scriptId":"u76"},
      "6e57e6a09e6a4c5cb0f4478ad45c4033":{
        "scriptId":"u77"},
      "edce9b88c1b84a97bcf179a7c5ba410a":{
        "scriptId":"u78"},
      "4d6529c5f2854300aa07a1c60ff2a181":{
        "scriptId":"u79"},
      "e11e63f0437e4e35a3583abef588e541":{
        "scriptId":"u80"},
      "4f9f006463574e26aba1e461594f7a34":{
        "scriptId":"u81"},
      "d11ed9864dd44c1c9b0ff5d5f05016b0":{
        "scriptId":"u82"},
      "1799b3c2583c4749b9b1214d15cc1eec":{
        "scriptId":"u83"}},
    "9a50b08c8ed344f4885e11ac78b12182":{
      "scriptId":"u84"}}});