<div class="stampcustomer">
	<a class="close">×</a>
	<form action="<?php echo $this->getUrl('stampcustomer/index/ajax'); ?>" method="post" id="ajaxstampcustomer_form">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="fieldset">
			<ul class="form-list">
				<li>
					<label for="a_state"><?php echo $this->__("注册区域"); ?></label>
					<?php $states = Mage::helper("stampcustomer")->getState(); ?>
					<?php if(count($states)>0): ?>
					<select name="a_state" id="a_state" class="form-control">
						<?php foreach($states as $index=>$state):?>
							<option value="<?php echo $index?>"> <?php echo $state?></option>
						<?php endforeach;?>
					</select>
					<?php else: ?>
					<input type="text" name="a_state" id="a_state" class="form-control" />
					<?php endif; ?>
				</li>
				<li>
					<label for="a_name"><?php echo $this->__("姓名"); ?></label>
					<input type="text" class="form-control" name="a_name" id="a_name" />
				</li>
				<li>
					<label for="a_company"><?php echo $this->__("公司"); ?></label>
					<input type="text" class="form-control" name="a_company" id="a_company" />
				</li>
				<li>
					<label for="a_certtype"><?php echo $this->__("专业类型"); ?></label>
					<?php $product = Mage::registry('current_product');?>
					<input type="text" class="form-control required-entry" name="a_certtype" id="a_certtype" value="<?php echo $product->getName(); ?>" />
				</li>
				<li>
					<label for="a_certsn"><?php echo $this->__("注册证书号"); ?></label>
					<input type="text" class="form-control" name="a_certsn" id="a_certsn" />
				</li>
				<li>
					<label for="a_stampsn"><?php echo $this->__("印章号"); ?></label>
					<input type="text" class="form-control" name="a_stampsn" id="a_stampsn" />
				</li>
			</ul>
		</div>
	</form>
	<div class="row">
	  <button type="button" class="col-xs-5 col-md-4 btn btn-lg btn-primary pull-left" onclick="AjaxStampcustomer.submit(this)"><?php echo $this->__(" 查询 ");?></button>
	  <button type="button" class="col-xs-5 col-md-4 sure btn btn-lg btn-success pull-right"><?php echo $this->__("选定");?></button>
	</div>
	<div class="results">

	</div>
</div>
<script type="text/javascript">
	//<!{CDATA[
		var AjaxStampcustomer  = new VarienForm('ajaxstampcustomer_form');
		AjaxStampcustomer.submit = function(button){
            if (this.validator.validate()) {
                var url = jQuery("#ajaxstampcustomer_form").attr('action');
				var a_name = jQuery("#a_name").val();
				var a_company = jQuery("#a_company").val();
				var a_certsn = jQuery("#a_certsn").val();
				var a_stampsn = jQuery("#a_stampsn").val();
				if(!a_name && !a_company && !a_certsn && !a_stampsn){
					jQuery(".stampcustomer .fieldset").append('<div class="validation-advice advice-required-entry-a" >姓名,公司,注册证书号,印章号至少要填写一个</div>');
					setTimeout(function () {
						jQuery(".stampcustomer div.advice-required-entry-a").remove();
					}, 2000);

				}else{
					jQuery.ajax({
						type: "POST",
						url: url,
						dataType: "json",
						data:jQuery("#ajaxstampcustomer_form").serialize(),
						success: function(json) {
							if(json.status){
								jQuery(".results").empty().append(json.html);
								jQuery(".sure").show();
							}else{
								jQuery(".results").empty().append(json.message);
								jQuery(".sure").hide();
							}
						}
					});
				}
            }
        }.bind(AjaxStampcustomer);
		jQuery(function($){
			$(".entry").click(function(){
				$(".stampcustomer").toggle();

			});
			$(".stampcustomer .close").click(function(){
				$(".stampcustomer").hide();
			})
		})
	//]}>
	</script>
